### ISSUE TITLE
Prevent refresh from losing progress

### ISSUE THREAD

**Issue by davehunt** [jonesnxt/kilordle#9]
Especially frustrating when scrolling to top causes all progress to be lost due to accidental pull to refresh. 😢

**Comment by jonesnxt** [comment]
Instead of logging to browser history, I decided to go with disabling pull to refresh to fix this.

I think this is the correct path as some people like to try multiple times to optimize, but pull to refresh is annoying.

https://github.com/jonesnxt/kilordle/commit/32e441bb01bfd67752eefc7078788dbfb9acc4b2
